openapi: 3.0.1
info:
  title: Example API
  description: Simple Ktor API with Swagger UI
  version: "1.0"
paths:
  /hello:
    get:
      summary: Returns a greeting.
      responses:
        '200':
          description: Successful Response
          content:
            text/plain:
              schema:
                type: string
