openapi: 3.0.3
info:
  title: Quotes API
  version: 1.0.0
  description: API for managing quotes and pending quotes
paths:
  /quotes:
    get:
      summary: Get all quotes
      responses:
        '200':
          description: List of quotes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quote'
        '404':
          description: No quotes found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      summary: Add one or more quotes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Quote'
                - type: array
                  items:
                    $ref: '#/components/schemas/Quote'
      responses:
        '201':
          description: Quote(s) created
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      summary: Delete a quote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Quote'
      responses:
        '200':
          description: Updated list of quotes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quote'

  /quotes/search:
    get:
      summary: Search quote by title
      parameters:
        - name: title
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Quote found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
        '400':
          description: Missing title
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Quote not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /quotes/random:
    get:
      summary: Get a random quote
      responses:
        '200':
          description: A random quote
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
        '404':
          description: No quotes found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /pending/quotes:
    get:
      summary: Get all pending quotes
      responses:
        '200':
          description: List of pending quotes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quote'
        '404':
          description: No pending quotes found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      summary: Add one or more pending quotes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Quote'
                - type: array
                  items:
                    $ref: '#/components/schemas/Quote'
      responses:
        '201':
          description: Pending quote(s) created
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      summary: Delete a pending quote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Quote'
      responses:
        '200':
          description: Updated list of pending quotes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quote'

  /pending/quotes/search:
    get:
      summary: Search pending quote by title
      parameters:
        - name: title
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Pending quote found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
        '400':
          description: Missing title
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Quote not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /pending/quotes/promote:
    post:
      summary: Promote one or more pending quotes to quotes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Quote'
                - type: array
                  items:
                    $ref: '#/components/schemas/Quote'
      responses:
        '201':
          description: Quote(s) promoted
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Quote:
      type: object
      properties:
        id:
          type: integer
        quoteText:
          type: string
        author:
          type: string
        quoteSource:
          type: string
        tags:
          type: array
          items:
            type: string
        createdAt:
          type: string
          format: date-time
        loggedBy:
          type: string
          nullable: true
      required:
        - id
        - quoteText
        - author
        - quoteSource
        - tags
        - createdAt

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        details:
          type: string
          nullable: true
      required:
        - error
