ktor:
    deployment:
        port: ${PORT}   # Railway sets this env var dynamically
        watch:
            - classes
    application:
        modules:
            - com.yourpackage.ApplicationKt.module  # Replace with your actual module

